export const QUERY_KEY = {
  bookInfo: 'bookInfo',
  reviewList: 'reviewList',
  memoDetail: 'memoDetail',
  reviewDetail: 'reviewDetail',
  wellList: 'wellList',
  storeItemList: 'storeItemList',
  profileDetail: 'profileDetail',
  wellDetail: 'wellDetail',
  wellItems: 'wellItems',
  memoList: 'memoList',
  myFrogs: 'myFrogs',
  reviewCount: 'reviewCount',
  comments: 'comments',
  childComments: 'childComments',
  feed: 'feed',
  profile: 'profile',
  followings: 'followings',
  followers: 'followers',
  searchResult: 'searchResult',
  points: 'points',
  explore: 'explore',
  searchWells: 'searchWells',
  firstMemoDetail: 'firstMemoDetail',
  profileFeed: 'profileFeed',
} as const;
