export const STORAGE_KEY = {
  JOIN_FORM_KEY: '@FROLOG_JOIN_FORM',
  FIND_FORM_KEY: '@FROLOG_FIND_FORM',
  TEST_ANSWER_KEY: '@FROLOG_TEST_ANSWER',
  TEMP_ACCOUNT_KEY: '@FROLOG_TEMP_ACCOUNT',
  LOGIN_CALLBACK: '@FROLOG_LOGIN_CALLBACK_URL',
  TEST_CALLBACK: '@FROLOG_TEST_CALLBACK',
  TEST_RESULT_FOR_EDIT: '@FROLOG_TEST_RESULT_FOR_EDIT',
  PROFILE_EDIT_FORM_KEY: '@FROLOG_PROFILE_EDIT_FORM',
  PROFILE_IS_EDITED: '@FROLOG_PROFILE_IS_EDITED',
} as const;
