export const JOIN_FORM_KEY = '@FROLOG_JOIN_FORM';
export const FIND_FORM_KEY = '@FROLOG_FIND_FORM';
export const TEST_ANSWER_KEY = '@FROLOG_TEST_ANSWER';
export const REMEMBER_ME_KEY = '@FROLOG_REMEMBER_ME';
export const TEMP_ACCOUNT_KEY = '@FROLOG_TEMP_ACCOUNT';
